[DS-3018] Add in multi-stage models
ShopRunner/collie pull request #22
Opened 2021-07-12 16:55 UTC by nathancooperjones

I am in the process of cleaning up Hanna's code she left behind. This PR is still very much in progress and _not_ ready to be reviewed yet! 

## Describe the big picture - why are we doing this?

## Any additional details to clarify code in the PR?

## How is this tested?

## Pull Request Checklist
 - [ ] Pull request includes a description of why we are doing this
 - [ ] ``CHANGELOG`` has been updated
 - [ ] Version in ``_version.py`` has been updated
 - [ ] All tests in the ``tests`` folder pass with a local build
 - [ ] ``README`` has been updated (if applicable)
 - [ ] Documentation in ``docs`` has been updated (if applicable)
 - [ ] ``requirements.txt`` and ``requirements-dev.txt`` have been recompiled (if applicable)
 - [ ] Docker image can be built using ``docker build -t collie_recs .``

## Screenshots or GIFs?

2021-07-13 21:48 UTC, sugi-chan requested changes
mostly just saying things look cool.... but have some questions and such. I will take another look through it tomorrow/later today lol

2021-07-13 21:48 UTC, sugi-chan commented on collie_recs/model/cold_start_matrix_factorization.py
> +    def set_stage(self, stage: str) -> None:
so bc of the way the cold start models arer built these are the only two stages... cool

2021-07-13 21:48 UTC, sugi-chan commented on collie_recs/model/hybrid_pretrained_matrix_factorization.py
> +        return self.embeddings[1].weight.data
ok so since this is happening everywhere im guessing its intentional., but we dont need to be detaching/moving things around on cpu and so on?

2021-07-13 21:48 UTC, sugi-chan commented on collie_recs/model/base/multi_stage_pipeline.py
> +    def _load_model_init_helper(self, *args, **kwargs) -> None:
ok so this works because at this pt we have a trained model and want to load it in as if it was the last stage?

2021-07-13 21:48 UTC, sugi-chan commented on collie_recs/model/neural_collaborative_filtering.py
> +        ), axis=1).detach()
i guess i commented on this twice at various pts

2021-07-13 22:35 UTC, nathancooperjones commented
I can't actually tag @htorrence as a reviewer on this PR, but in case driving is really boring and you'd rather look at code for free, here you go!!

2021-07-14 14:20 UTC, nathancooperjones commented on collie_recs/model/base/multi_stage_pipeline.py
> +        if optimizer_config_list is not None:
Yeah, this is not clear right now. It should only be `None` if we are loading in a model - I'll fix that now.

2021-07-14 14:22 UTC, nathancooperjones commented on collie_recs/model/base/trainer.py
> +            for optimizer_idx, optimizer in enumerate(self.optimizer.optimizers):
wait - are there optimizers that don't step on batches?

2021-07-14 14:22 UTC, nathancooperjones commented on collie_recs/model/neural_collaborative_filtering.py
> +        ), axis=1).detach()
I think here it's okay if these are on the device - they get used in the `item_item_similarity` method and we move it to CPU there.

2021-07-14 14:24 UTC, nathancooperjones commented on tests/fixtures/model_fixtures.py
> +                                                  lr=1e-2,
They should have been swapped from the getgo - typo!

2021-07-14 14:25 UTC, nathancooperjones commented on collie_recs/model/base/multi_stage_pipeline.py
> +    def _load_model_init_helper(self, *args, **kwargs) -> None:
yes, exactly!

2021-07-14 14:34 UTC, sugi-chan commented on collie_recs/model/base/trainer.py
> +            for optimizer_idx, optimizer in enumerate(self.optimizer.optimizers):
oh wait brain was thinking badly lolll nvm

2021-07-14 14:34 UTC, sugi-chan commented
I feel like doing PR reviews while driving could be bad

2021-07-14 14:36 UTC, nathancooperjones commented
> I feel like doing PR reviews while driving could be bad

I mean, who's to say!

2021-07-14 19:25 UTC, sugi-chan approved these changes
I think this looks reasonable? /my brain is kinda going to mush after looking at it for awhile...

![](https://media1.tenor.com/images/856166a46d06c4d77078e63e94e0e2d5/tenor.gif?itemid=11048773)

2021-07-14 19:55 UTC, sugi-chan approved these changes
tutorials seem good, I added a question about advancing through stages since someone might break it cuz ppl are bad? haha

2021-07-14 19:55 UTC, sugi-chan commented on collie/model/base/multi_stage_pipeline.py
> +    def advance_stage(self) -> None:
ok so was wondering what would happen if you like advanced past the len of the stage list or w/e... but I feel like thats kinda on a user... also since you call this it means you could in theory run a stage for more epochs if u needed to which is good. 

One thought would be if there was any interest in being able to go back a stage, but in theory a user could make use of the `set_tage` method which seems k

2021-07-14 19:56 UTC, sugi-chan commented on tutorials/06_multi_stage_models.ipynb
> +{
<p>this is pretty great (setting all the seeds for nicer reproducibility is sweet)</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/ShopRunner/collie_recs/pull/22/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='10'/>

2021-07-14 19:56 UTC, sugi-chan commented on tutorials/06_multi_stage_models.ipynb
> +{
<p><s>so in the first stage of training collie doesnt say the stage name, which it does in the following ones. I think that is a good quality of life improvement if not overly annoying to do.</s></p><p> </p><p>Ah ok it does get put higher up when initialized. I guess that works well. cool</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/ShopRunner/collie_recs/pull/22/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='14'/>

2021-07-14 19:56 UTC, sugi-chan commented on tutorials/06_multi_stage_models.ipynb
> +{
<p>nice addition to show why cold start is valuable</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/ShopRunner/collie_recs/pull/22/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='29'/>

2021-07-14 21:30 UTC, nathancooperjones commented on collie/model/cold_start_matrix_factorization.py
> +        if self.hparams.stage == 'item_buckets':
I _totally_ agree - I feel like Octopod is a real natural candidate for this sort of thing.

2021-07-14 21:31 UTC, nathancooperjones commented on collie/model/hybrid_pretrained_matrix_factorization.py
> +            self._move_any_external_data_to_device()
Eh, it's a bit hacky but the cleanest way I could do it for both `CollieTrainer` and `CollieMinimalTrainer`. Let me know if you think this is bad.

2021-07-14 21:31 UTC, nathancooperjones commented on collie/model/cold_start_matrix_factorization.py
> +            if current_stage == 'item_buckets' and stage == 'no_buckets':
yes, exactly!

2021-07-15 02:38 UTC, nathancooperjones commented on collie/model/base/multi_stage_pipeline.py
> +    def advance_stage(self) -> None:
I agree, it should be on the user to not advance past the last stage, or else error. 

I think there shouldn't ever have to be a situation you reverse a stage (at least for now), but if someone needs to, they can just use `set_stage` for sure ¯\\_(ツ)_/¯

2021-07-15 14:47 UTC, merged