Fix unit tests error, failures, and warnings
ShopRunner/collie pull request #32
Opened 2021-08-10 04:54 UTC by nathancooperjones

## Describe the big picture - why are we doing this?
PyTorch Lightning updated to version 1.4.0 and ended up introducing some breaking changes that affected Collie unit tests. Those were solved by replacing `max_steps -> max_epochs` (which I believe is actually a bug on the PyTorch Lightning side of things - opening an `Issue` about it in that repo soon) and by replaxing `max_epochs += X -> increase_max_epochs(X)``. Annoying, but ¯\\_(ツ)_/¯ at least it works now 🎉 

## Any additional details to clarify code in the PR?
Any instances of `max_epochs += X` should be replaced. If I missed any, let me know! 

## How is this tested?
With many unit tests! 

## Pull Request Checklist
 - [X] Pull request includes a description of why we are doing this
 - [X] ``CHANGELOG`` has been updated
 - [X] Version in ``_version.py`` has been updated
 - [X] All tests in the ``tests`` folder pass with a local build
 - [ ] ``README`` has been updated (if applicable)
 - [ ] Documentation in ``docs`` has been updated (if applicable)
 - [X] ``requirements.txt`` and ``requirements-dev.txt`` have been recompiled (if applicable)
 - [X] Docker image can be built using ``docker build -t collie .``

## Screenshots or GIFs?
![](https://c.tenor.com/B7TP3JU7qcAAAAAC/fixed.gif)

2021-08-10 04:55 UTC, nathancooperjones commented
Tagging all remaining SR DS people to review. If anyone is able to review this so we can start merging other PRs into Collie, that would be great! 

Once this is approved, feel free to merge, since I no longer have permissions to do so 🙇‍♂️

2021-08-10 12:53 UTC, gsganden commented
How do you feel about the failing codecov check?

2021-08-10 13:24 UTC, nathancooperjones commented
> How do you feel about the failing codecov check?

Normally, we want all changes in a PR to be thoroughly tested, but because I made two changes here that could only be tested by installing different versions of PyTorch Lightning, I think it's okay if we have this one-time exception where the Codecov diff target is not what we normally want. My vote is to keep it failed here and continue merging this and other PRs in. How does that sound to you?

2021-08-10 13:38 UTC, nathancooperjones commented
BTW, I created the PyTorch Lightning Issue that this PR attempts to fix within Collie [here](https://github.com/PyTorchLightning/pytorch-lightning/issues/8839) 🎉

2021-08-10 16:59 UTC, gsganden requested changes
I'm concerned that there's nothing to stop folks from assigning to `trainer.max_epochs`, which if I understand correctly wouldn't have the desired effect. I think using [this approach](https://www.programiz.com/python-programming/property) to turn `increase_max_epochs` into a setter would avoid that problem. Does that seem like a good solution to you?

2021-08-10 18:12 UTC, gsganden commented
@Menna13 @mcundiff3 @sugi-chan I'll take responsibility for this review, but feel free to chime in if you like.

2021-08-11 14:00 UTC, nathancooperjones commented
> I'm concerned that there's nothing to stop folks from assigning to `trainer.max_epochs`, which if I understand correctly wouldn't have the desired effect. I think using [this approach](https://www.programiz.com/python-programming/property) to turn `increase_max_epochs` into a setter would avoid that problem. Does that seem like a good solution to you?

I think I'm a bit stuck then - the `property` can't have the same name as the attribute it is changing (see [here](https://stackoverflow.com/questions/36931415/using-properties-in-python-classes-cause-maximum-recursion-depth-exceeded). 

Right now with the newest PyTorch Lightning API, if we try to set `trainer.max_epochs` we get an `AttributeError`. What do you think is the best solution for this going forward?

2021-08-16 19:46 UTC, gsganden requested changes
For our records: after talking it over we think there is a solution using `@properties`. @nathancooperjones will give it a try.

2021-08-16 20:06 UTC, nathancooperjones commented
> For our records: after talking it over we think there is a solution using `@properties`. @nathancooperjones will give it a try.

From this conversation, we landed on a solution that seems to work reliably with the PyTorch Lightning API pre- and post-changes to the `max_epochs` attribute. And for the record, @gsganden was totally right in his approach! 

<img width="964" alt="Screen Shot 2021-08-16 at 2 51 32 PM" src="https://user-images.githubusercontent.com/31417712/129622468-686808b2-18b5-4652-869b-1b904f837a55.png">
<img width="920" alt="Screen Shot 2021-08-16 at 2 58 05 PM" src="https://user-images.githubusercontent.com/31417712/129622477-5b0b7760-b285-4cb8-982f-611e8d92d7e0.png">
<img width="927" alt="Screen Shot 2021-08-16 at 2 56 58 PM" src="https://user-images.githubusercontent.com/31417712/129622486-6b0b717b-d711-4694-bfe9-eef042e60a19.png">

2021-08-16 20:46 UTC, gsganden requested changes

2021-08-16 20:46 UTC, gsganden commented on collie/model/base/trainer.py
> +        self._max_epochs = max_epochs
I think we don't need this line? I believe `super().__init__(**kwargs)` will do `self.max_epochs = max_epochs`, which will run our setter. At least that's the way it seems to be working in my simplified dummy example:

```
class LightningThing:
    def __init__(self, max_epochs):
        self.max_epochs = max_epochs

    @property
    def max_epochs(self):
        return self.max_epochs


class OurThing(LightningThing):
    def __init__(self, max_epochs):
        super().__init__(max_epochs)

    @property
    def max_epochs(self):
        try:
            return self.fit_loop.max_epochs
        except AttributeError:
            return self._max_epochs

    @max_epochs.setter
    def max_epochs(self, value):
        try:
            self.fit_loop.max_epochs = value + 1
        except AttributeError:
            self._max_epochs = value + 1


t = OurThing(max_epochs=3)

print(t.max_epochs)

#> 4
```

2021-08-16 20:46 UTC, gsganden commented on collie/model/base/trainer.py
> +
Is the `property` implementation doing anything for us on this class?

2021-08-16 20:46 UTC, gsganden commented on collie/model/base/trainer.py
> +                 max_epochs: int = 10,
It looks to me like the previous default was 1000 (https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/trainer/trainer.py#L377). If so, should we be concerned about that behavior change?

2021-08-16 20:46 UTC, gsganden commented on collie/model/base/trainer.py
> +        self._max_epochs = max_epochs
IIUC, we are meant to do `self.max_epochs = max_epochs`. That triggers the setter, which does `self._max_epochs = max_epochs` behind the scenes. Only the property and the setter touch `self._max_epochs`.

2021-08-16 20:46 UTC, gsganden commented on tests/fixtures/model_fixtures.py
> +                                               max_epochs=1,
What's up with `max_steps` vs. `max_epochs`? I still a little hazy on how that change fits in and whether we are handling it in a backward-compatible way.

2021-08-16 21:19 UTC, nathancooperjones commented on collie/model/base/trainer.py
> +                 max_epochs: int = 10,
I think for recommendations models, we would never need to train that many epochs. I think setting a more reasonable default of `10` here for the recommendations-specific `Trainer` is probably the right move going forward.

2021-08-16 21:19 UTC, nathancooperjones commented on collie/model/base/trainer.py
> +
No, but I figured it would be good to keep the two `Trainer` classes consistent in this respect. What do you think?

2021-08-16 21:29 UTC, nathancooperjones commented on tests/fixtures/model_fixtures.py
> +                                               max_epochs=1,
See https://github.com/PyTorchLightning/pytorch-lightning/issues/8839 for the reason we had to make this change.

2021-08-16 21:29 UTC, nathancooperjones commented on tests/fixtures/model_fixtures.py
> +                                               max_epochs=1,
It's a fully backward-compatible change, just something we had to do because of a recently introduced PyTorch Lightning bug.

2021-08-16 21:29 UTC, gsganden commented on collie/model/base/trainer.py
> +
The external behavior of the two classes will be the same either way, right? I would expect that adding an extra wrinkle that isn't doing anything to the implementation of this one would cause confusion more than it would help.

2021-08-16 21:32 UTC, gsganden commented on collie/model/base/trainer.py
> +                 max_epochs: int = 10,
OK. I think technically this change breaks backwards compatibility and thus strictly speaking should invoke a major version bump, but maybe that would be silly? I guess we could claim that it's sort of a bug fix, since `1000` was never really intended to be the default?

2021-08-17 23:42 UTC, gsganden approved these changes
LGTM. I would take out the property stuff in `CollieMinimalTrainer`, but I'm OK with it if you like it.

2021-08-17 23:44 UTC, merged